# Generated by Django 4.2.7 on 2024-01-03 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 3, 13, 29, 10, 640346, tzinfo=datetime.timezone.utc)),
        ),
    ]
