# Generated by Django 4.2.7 on 2024-01-04 14:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_excerpt_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 14, 55, 25, 773269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('measurement', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='blog.post')),
            ],
        ),
    ]
