# Generated by Django 4.2.7 on 2024-01-04 23:08

import datetime
from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_date_posted_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=djrichtextfield.models.RichTextField(blank=True, max_length=8000),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 4, 23, 7, 59, 964526, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
