# Generated by Django 4.2.7 on 2024-01-09 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_ingredients_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_pics', verbose_name='default.jpg'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 9, 55, 51, 715824, tzinfo=datetime.timezone.utc)),
        ),
    ]
