# Generated by Django 4.2.7 on 2024-01-12 01:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_date_posted_recipebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='color',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 1, 52, 55, 793069, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 12, 1, 52, 55, 793756, tzinfo=datetime.timezone.utc)),
        ),
    ]
