# Generated by Django 4.2.7 on 2024-01-24 13:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_rename_body_comment_content_alter_post_date_posted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 13, 7, 50, 695499, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='recipebook',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 13, 7, 50, 696143, tzinfo=datetime.timezone.utc)),
        ),
    ]
